#!/usr/bin/env python3
from __future__ import annotations

import argparse
import pathlib
import struct

OP_HALT = 0x00
OP_PUSH_I64 = 0x01
OP_ADD = 0x02
OP_TRAP = 0x30


def encode_push_i64(value: int) -> bytes:
    return bytes([OP_PUSH_I64]) + struct.pack("<q", value)


def build_program() -> bytes:
    # exit code = 5 + 7 = 12
    return b"".join(
        [
            encode_push_i64(5),
            encode_push_i64(7),
            bytes([OP_ADD]),
            bytes([OP_HALT]),
        ]
    )

def build_trap_program() -> bytes:
    return bytes([OP_TRAP]) + struct.pack("<I", 1337)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate sample sandbox bytecode program.")
    parser.add_argument(
        "--program",
        default="add",
        choices=["add", "trap"],
        help="Program shape to generate",
    )
    parser.add_argument(
        "--out",
        default="examples/sample_add_exit.bc",
        help="Output path for generated bytecode file",
    )
    args = parser.parse_args()

    if args.program == "add":
        payload = build_program()
    else:
        payload = build_trap_program()

    out_path = pathlib.Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(payload)
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
